import {
  createFilecoinAgent,
  prepareStorageInputSchema,
  retrieveInputSchema,
  storeFileInputSchema,
  storeTextInputSchema,
  verifyInputSchema,
  type FilecoinAgentConfig
} from "@filecoin-agent/core";
import { McpServer } from "@modelcontextprotocol/server";
import { toMcpJsonResult } from "./toolResult.js";

export function createFilecoinMcpServer(config: FilecoinAgentConfig) {
  const storage = createFilecoinAgent(config);
  const server = new McpServer({ name: "filecoin-agent", version: "0.1.0" });

  server.registerTool(
    "filecoin_store_text",
    {
      title: "Store text on Filecoin",
      description: "Store short text generated by an AI agent on Filecoin Onchain Cloud. This may spend storage funds when spending policy allows it.",
      inputSchema: storeTextInputSchema
    },
    async (input) => toMcpJsonResult(await storage.storeText(input))
  );

  server.registerTool(
    "filecoin_store_file",
    {
      title: "Store a local file on Filecoin",
      description: "Store a readable local file on Filecoin Onchain Cloud. Use only for paths the host process is allowed to read.",
      inputSchema: storeFileInputSchema
    },
    async (input) => toMcpJsonResult(await storage.storeFile(input))
  );

  server.registerTool(
    "filecoin_retrieve",
    {
      title: "Retrieve data from Filecoin",
      description: "Retrieve data by PieceCID. Prefer outputPath for large content so the agent does not print large byte arrays.",
      inputSchema: retrieveInputSchema
    },
    async (input) => {
      const result = await storage.retrieve(input);
      return toMcpJsonResult({ ...result, bytes: result.bytes ? `[${result.bytes.byteLength} bytes]` : undefined });
    }
  );

  server.registerTool(
    "filecoin_verify",
    {
      title: "Verify Filecoin storage",
      description: "Verify whether a PieceCID appears stored according to Filecoin Onchain Cloud/PDP-oriented evidence exposed by the backend.",
      inputSchema: verifyInputSchema
    },
    async (input) => toMcpJsonResult(await storage.verify(input))
  );

  server.registerTool(
    "filecoin_prepare_storage",
    {
      title: "Prepare Filecoin storage balance",
      description: "Estimate and prepare storage balance/approval for upcoming uploads. This may create a transaction when configured with a real backend.",
      inputSchema: prepareStorageInputSchema
    },
    async (input) => toMcpJsonResult(await storage.prepareStorage(input))
  );

  server.registerTool(
    "filecoin_balance",
    {
      title: "Check Filecoin storage balance",
      description: "Check FIL/USDFC balance and storage runway when the backend supports it."
    },
    async () => toMcpJsonResult(await storage.getBalance())
  );

  return server;
}
